ln -s ~/.dotfiles/.zshprofile ~/.zshprofile
ln -s ~/.dotfiles/.vimrc ~/.vimrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc
ln -s ~/.dotfiles/.vim ~/.vim
ln -s ~/.dotfiles/linux/kitty.conf ~/.config/kitty/kitty.conf
ln -s ~/.dotfiles/linux/hyprpaper.conf ~/.config/hypr/hyprpaper.conf
ln -s ~/.dotfiles/linux/hyprland.conf ~/.config/hypr/hyprland.conf
ln -s ~/.dotfiles/linux/waybar ~/.config/waybar
ln -s ~/.dotfiles/macos/sketchybar ~/.config/sketchybar/
ln -s ~/.dotfiles/macos/sketchybar/plugins ~/.config/sketchybar/plugins
