theme="snazzy"

[editor]
end-of-line-diagnostics = "hint"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]#, "diff"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-progress-messages = true
display-inlay-hints	= true

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

