theme="snazzy"

[editor]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-progress-messages = true
display-inlay-hints	= true

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true

[keys.select]
y = ["yank", ":clipboard-yank"]
