#!/bin/bash

export BACKGROUND_COLOR=0x50dbc9ff
export BORDER_COLOR=0x80c4a7e7
export HIGHLIGHT_COLOR=0xffdbc9ff
export BLUR_RADIUS=15
export CORNER_RADIUS=0

export ITEM_TOP_PADDING=5
export FAR_LEFT_ITEM_PADDING=20
export FAR_RIGHT_ITEM_PADDING=20