#!/bin/bash

source "$CONFIG_DIR/settings.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=33               \
                 position=top            \
                 sticky=on               \
                 color=0x0               \
                 notch_offset=26         \
                 padding_left=0          \
                 padding_right=0         \
                 topmost=true

sketchybar --default updates=when_shown                    \
                     icon.font="SF Pro Rounded:Bold:14.0"  \
                     icon.color=0xff000000               \
                     label.font="SF Pro Rounded:Bold:14.0" \
                     label.color=0xff000000                \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4


##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15" "16")

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid center                                 \
             --set space.$sid associated_space=$sid                      \
                              background.color=$BACKGROUND_COLOR                \
                              background.corner_radius=7                 \
                              width=25 \
                              background.height=7 \
                              background.drawing=on                     \
                              background.border_color=0x952a2d3d        \
                              background.border_width=1                 \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

# sketchybar --add item front_app left                               \
#            --set front_app       script="$PLUGIN_DIR/front_app.sh" \
#                                  icon.drawing=off                  \
#                                  background.color=$BACKGROUND_COLOR \
#                                  background.corner_radius=7 \
#                                  blur_radius=$BLUR_RADIUS \
#                                  background.border_color=0x80c4a7e7 \
#                                  background.border_width=1 \
#            --subscribe front_app front_app_switched

# # Add all of the right bar items
# source "$ITEM_DIR/clock.sh"
# source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/battery.sh"

sketchybar --update
